CUR_DIR := .
SOURCE_DIR := $(CUR_DIR)/src
BIN_DIR := $(CUR_DIR)/bin

bt1:
	gcc -o $(BIN_DIR)/bai1 $(SOURCE_DIR)/bai1.c

bt2:
	gcc -o $(BIN_DIR)/bai2 $(SOURCE_DIR)/bai2.c

bt3:
	gcc -o $(BIN_DIR)/bai3 $(SOURCE_DIR)/bai3.c

clean:
	rm -rf $(BIN_DIR)/*