CUR_DIR := .
SOURCE_DIR := $(CUR_DIR)/src
BIN_DIR := $(CUR_DIR)/bin

bt1:
	gcc -o $(BIN_DIR)/bai1 $(SOURCE_DIR)/bai1.c

bt3:
	gcc -o $(BIN_DIR)/bai3 $(SOURCE_DIR)/bai3.c

bt4:
	gcc -o $(BIN_DIR)/bai4 $(SOURCE_DIR)/bai4.c

clean:
	rm -rf $(BIN_DIR)/*