CUR_DIR := .
SOURCE_DIR := $(CUR_DIR)/src
BIN_DIR := $(CUR_DIR)/bin

CFLAGS := -pthread

bt1:
	gcc -o $(BIN_DIR)/bai1 $(SOURCE_DIR)/bai1.c $(CFLAGS)

bt2:
	gcc -o $(BIN_DIR)/bai2 $(SOURCE_DIR)/bai2.c $(CFLAGS)

bt3:
	gcc -o $(BIN_DIR)/bai3 $(SOURCE_DIR)/bai3.c $(CFLAGS)

bt4:
	gcc -o $(BIN_DIR)/bai4 $(SOURCE_DIR)/bai4.c $(CFLAGS)

bt5:
	gcc -o $(BIN_DIR)/bai5 $(SOURCE_DIR)/bai5.c $(CFLAGS)

bt6:
	gcc -o $(BIN_DIR)/bai6 $(SOURCE_DIR)/bai6.c $(CFLAGS)

clean:
	rm -rf $(BIN_DIR)/*